image: node:14-slim

definitions:
  caches:
    npm: $HOME/.npm

stepdefinitions:
  - tests: &tests
      name: Run tests and quality gate
      script:
        - npm ci --prefer-offline --no-audit
        - npm run test
        - npm run prettier
        - npm run lint
  - publish-npm: &publish-npm
      name: Build and publish npm package
      caches:
        - npm
      script:
        - npm ci --prefer-offline --no-audit
        - npm run build
        - pipe: atlassian/npm-publish:0.2.0
          variables:
            EXTRA_ARGS: "--access public"
            NPM_TOKEN: $NPM_TOKEN
pipelines:
  default:
    - step: *tests
  pull-requests:
    '**' :
      - step: *tests
  tags:
    v*:
      - step: *tests
      - parallel:
          - step: *publish-npm
